sonar.projectKey=CI-CD-Hello-World
sonar.projectName=CI-CD-Hello-World
sonar.sources=app.py
sonar.tests=test_app.py
sonar.python.version=3
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=reports/junit.xml
